# in hosts file
#
# [rabbitmq]
# rabbitmq host
#
# [celery]
# celery worker host
#
# ansible-playbook -i hosts -u <user_name> setup.yaml

---
- hosts: celery
  become: yes
  become_user: root
  tasks:
  - name: Install celery worker dependencies
    yum:
      name: "{{ packages }}"
      update_cache: yes
    vars:
      packages:
      - python34
      - python34-pip
      - python-virtualenv
      - git
      - redis

# after install, change /etc/redis.conf to bind ip, open firewall
#
# sudo iptables -A INPUT -p tcp --dport 6379 -s xxx.xxx.xxx.xxx -j ACCEPT
# sudo iptables -A INPUT -p tcp --dport 6379 -j DROP

- hosts: rabbitmq
  become: yes
  become_user: root
  tasks:
  - name: Install irods, rabbitmq, and redis dependencies
    yum:
      name: "{{ packages }}"
      update_cache: yes
    vars:
      packages:
      - rabbitmq-server
      - redis
  - name: Start redis service
    service:
      name: redis
      state: restarted

- hosts: celery
  user: xuhao
  vars:
    python_packages:
      - celery
      - progressbar2
      - python-redis-lock
      - python-irodsclient
    venv_path: "~/venv"
    repo_dir: "~/icai"
  tasks:
  - name: Clone repository
    git:	
      repo: "https://github.com/irods/irods_capability_automated_ingest"
      version: master
      dest: "{{repo_dir}}"
  - name: Install python dependencies
    pip:
      name: "{{ python_packages }}"
      virtualenv: "{{venv_path}}"
#  - name: Start celery worker